### PR TITLE
Add support for XCode10 (Swift 4.2)

### PR DESCRIPTION
**Pull request by markus-mohemian**
I have updated the project to support Swift 4.2. The edits are backwards compatible to Swift 4.0
Signed-off-by: Markus Bürgler <markus.buergler@mohemian.com>

### CODE REVIEW

**Comment by markus-mohemian** [comment]
@i-schuetz Would be great if we could merge that soon. Would like to update my projects to Swift 4.2 😄

**Comment by i-schuetz** [comment]
Thanks @markus-mohemian! Do you think we really need the backwards compatibility with Swift 4? This library isn't updated so frequently lately and if they don't want to upgrade Swift they just have to not upgrade the library...

**Comment by markus-mohemian** [comment]
@i-schuetz, that's right. Maybe I was too eager to get this merged. 😆 
I have updated the branch and removed the backwards compatibility, as updates are not that often.
Thanks for pointing that out.

**Comment by i-schuetz** [comment]
Thanks!

**Pull request merged**
