### PR TITLE
Support NSAttributedString on label of pie chart

### PR DESCRIPTION
**Pull request by studiogaram**
I want to using label with attributed string with name (issue #8).
So, the following tasks were carried out :

1. add 'name' property on PieSliceModel to identify as text
2. support NSAttributedString to use label better without modifying labelGenerator on PieChartLabelSettings.swift

you can create slice model as:
`
PieSliceModel(value: 2, color: colors[2]) // previous
`
or
`
PieSliceModel(name: "fff", value: 2, color: colors[0]) // this time
`

and you can use attributedText as:

        let categoryAttr = [
            NSFontAttributeName: UIFont.systemFont(ofSize: 8, weight: UIFontWeightLight),
            NSForegroundColorAttributeName: UIColor.blue
        ]

        let percentageAttr = [
            NSFontAttributeName: UIFont.systemFont(ofSize: 8),
            NSForegroundColorAttributeName: UIColor.black
        ]

        textLayerSettings.label.type = .attributed
        textLayerSettings.label.attributedTextGenerator = {slice in
            let categoryString = NSMutableAttributedString(string: slice.data.model.name ?? "", attributes: categoryAttr)
            let percentageString = NSMutableAttributedString(string:
                formatter.string(from: slice.data.percentage * 100 as NSNumber).map{"\($0)%"} ?? "", attributes: percentageAttr)
            categoryString.append(percentageString)
            
            return categoryString
        }

without textGenerator. 

Thank you!

### CODE REVIEW

**Comment by i-schuetz** [comment]
Supporting attributed string is a good idea! I think we could simplify the 2 mutually exclusive variables by having 1 defined in terms of the other, like this:

```swift
public class PieChartLabelSettings {
    
    public var textColor: UIColor = UIColor.black
    public var bgColor: UIColor = UIColor.clear
    public var font: UIFont = UIFont.boldSystemFont(ofSize: 20)
    public var attributedTextGenerator: (PieSlice) -> NSAttributedString = {NSAttributedString(string: "\($0.data.model.value)")}

    // Optional custom label - when this is set presentations settings (textColor, etc.) are ignored
    public var labelGenerator: ((PieSlice) -> UILabel)?
}

// MARK: - Convenience

extension PieChartLabelSettings {
    
    public var textGenerator: (PieSlice) -> String {
        set {
            attributedTextGenerator = {slice in
                return NSAttributedString(string: newValue(slice))
            }
        }
        get {
            return {[weak self] slice in
                self?.attributedTextGenerator(slice).string ?? ""
            }
        }
    }
}
```

What do you think (it's untested)?

**Comment by studiogaram** [comment]
Thank you very much for checking. I like to organize mutually exclusive variables like this.
It's much better to do this.

**Comment by i-schuetz** [comment]
Note completely sure what you mean with "this", but I'm assuming you mean the approach in your PR.

To be clearer, I think it adds unnecessary complexity, both to the implementation and the interface (you have to do switch case in multiple places, user has to be aware that they have to set `Type` - what if they don't do it and pass an attributed generator? Is it clear enough that `type` variable refers only to the label generator? Etc.) While having one defined in terms of the other simplifies things significantly (you don't need switch case, it's not possible for user to do mistakes, etc.).

**Comment by i-schuetz** [comment]
Actually, to maintain mutually exclusive state, we can use enums with associated values. We can also add an internal method that converts the result of both to attributed string, such that we don't have to make switch case in multiple places

```swift
public class PieChartLabelSettings {
    
    public enum PieChartLabelTextGenerator {
        case plain((PieSlice) -> String)
        case attributed(((PieSlice) -> NSAttributedString))
    }

    var textGenerator: PieChartLabelTextGenerator = .plain({slice in
        return "\(slice.data.model.value)"
    })
        
    public var textColor: UIColor = UIColor.black
    public var bgColor: UIColor = UIColor.clear
    public var font: UIFont = UIFont.boldSystemFont(ofSize: 20)

    // Optional custom label - when this is set presentations settings (textColor, etc.) are ignored
    public var labelGenerator: ((PieSlice) -> UILabel)?
}

extension PieChartLabelSettings {

    func attributedString(slice: PieSlice) -> NSAttributedString {
        switch textGenerator {
        case .plain(let f): return NSAttributedString(string: f(slice))
        case .attributed(let f): return f(slice)
        }
    }
}
```

**Comment by i-schuetz** [comment]
Yet another and IMO better idea would be to use a common protocol. The only problem with this is that it adds a method to the public interface of `String` / `NSAttributedString`. Not sure if there's a way to avoid of that.

First we create a common protocol `AttributedStringRepresentable` and make `NSAttributedString` and `String` conform to it:

```swift
public protocol AttributedStringRepresentable {
    var attributedString: NSAttributedString {get}
}

extension NSAttributedString: AttributedStringRepresentable {
    public var attributedString: NSAttributedString {
        return self
    }
}

protocol StringRepresentable {
    var value: String {get}
}

extension String: StringRepresentable {
    var value: String {
        return self
    }
}

extension String: AttributedStringRepresentable {
    public var attributedString: NSAttributedString {
        return NSAttributedString(string: value)
    }
}
```

Then we need only 1 generator, that produces a `AttributedStringRepresentable`:

`public var textGenerator: ((PieSlice) -> AttributedStringRepresentable)?`

Now we can pass `textGenerator` without having to care if it's a plain or attributed string:

```swift
// plain
textLayerSettings.label.textGenerator2 = {slice in
    return "\(slice.data.percentage)"
}

// attributed
textLayerSettings.label.textGenerator2 = {slice in
    return NSAttributedString(string: "\(slice.data.percentage)")
}
```

**Comment by studiogaram** [comment]
I think there has been a little misunderstanding.Rather than using enum, it would be appropriate to use attributedString as the way you suggested.

**Comment by studiogaram** [comment]
But the way you last posted it is also very good and attractive because of managing NSAttributedString with only one function(textGenerator). Maybe there are several ways to present NSAttributedString, but the last one you posted is the most reasonable.

**Comment by i-schuetz** [comment]
So far I'm not finding a way to use the extensions approach without the `attributedString` variable ending in the public interface of `String`/ `NSAttributedString` and this is a bad practice. Imagine in your `NSAttributedString` autocompletions seeing a variable called `attributedString`! 

It seems then that the best approach is the one I first suggested, having both `attributedTextGenerator` and a `textGenerator`.

Unless you have an idea how we can use the extension without adding junk to the public api.

If you don't you can implement what I suggested and I'll merge it. Please squash the commits when you do!

**Comment by studiogaram** [comment]
Sorry for late reply. Last weekend I was working on your first answer, and suddenly I wondered.

There is no problem with saving string or NSAttributedString without enum type in `PieChartLabelSettings.swift` as you said.

However, in `PieLineTextLayer.swift` or `PiePlainTextLayer.swift,` they have to use `label.text` or `label.attributedText` to set label. 
And if string in the pie was not typed explicitly, they couldn’t choose the method that will set label (use `.text` or `.attributedText)`

I think the type should be declared for the reason. What do you think?

**Comment by i-schuetz** [comment]
Hi. The idea is to use internally always only attributed string. So we use only `attributedText`. This would also mean that you have to set the label settings (`textColor`, `font`) as attributes where the plain string is converted to attributed string. Am I missing something?

**Comment by i-schuetz** [comment]
What happened with this?

**Pull request closed without merging**
